[constants]
devkitpro = '/opt/devkitpro'
devkitarm = devkitpro / 'devkitARM'
prefix = devkitarm / 'bin' / 'arm-none-eabi-'

ctrulib = devkitpro / 'libctru'
portlibs = devkitpro / 'portlibs/3ds'

archflags = ['-march=armv6k', '-mtune=mpcore', '-mfloat-abi=hard', '-mtp=soft']

[properties]
pkg_config_libdir = portlibs / 'lib/pkgconfig'

[binaries]
c       = prefix + 'gcc'
cpp     = prefix + 'g++'
ar      = prefix + 'gcc-ar'
as      = prefix + 'as'
ld      = prefix + 'ld'
nm      = prefix + 'nm'
objcopy = prefix + 'objcopy'
objdump = prefix + 'objdump'
ranlib  = prefix + 'ranlib'
readelf = prefix + 'readelf'
size    = prefix + 'size'
strings = prefix + 'strings'
strip   = prefix + 'strip'

pkg-config = portlibs / 'bin/arm-none-eabi-pkg-config'

[built-in options]
c_args        = archflags + ['-mword-relocations', '-I' + ctrulib / 'include', '-D__3DS__']
c_link_args   = archflags + ['-specs=3dsx.specs', '-L' + ctrulib / 'lib', '-lctru']
cpp_args      = archflags + ['-mword-relocations', '-I' + ctrulib / 'include', '-D__3DS__']
cpp_link_args = archflags + ['-specs=3dsx.specs', '-L' + ctrulib / 'lib', '-lctru']

[project options]
# debug_ui = false
# profiling = false

[host_machine]
system = 'n3ds'
cpu_family = 'arm'
cpu = 'armv6k'
endian = 'little'

[target_machine]
system = 'n3ds'
cpu_family = 'arm'
cpu = 'armv6k'
endian = 'little'
