// GENERATED BY buildSongs.py
// DO NOT EDIT DIRECTLY

#include "audio_files.h"

const char* SoundEffectPaths[] = {
    "assets/menuCancel.wav",
    "assets/cool.wav",
    "assets/regret.wav",
    "assets/backToBackQuad.wav",
    "assets/time.wav",
    "assets/shift.wav",
    "assets/backToBackTSpin.wav",
    "assets/gameover.wav",
    "assets/hold.wav",
    "assets/multiClear.wav",
    "assets/perfectris.wav",
    "assets/perfectClear.wav",
    "assets/ultimatris.wav",
    "assets/rotate.wav",
    "assets/win.wav",
    "assets/initial.wav",
    "assets/tSpin.wav",
    "assets/menuConfirm.wav",
    "assets/go.wav",
    "assets/invalid.wav",
    "assets/menuMove.wav",
    "assets/decahexatris.wav",
    "assets/clear.wav",
    "assets/ready.wav",
    "assets/end.wav",
    "assets/levelUPsound.wav",
    "assets/double.wav",
    "assets/tSpinMini.wav",
    "assets/youLose.wav",
    "assets/dodecatris.wav",
    "assets/octoris.wav",
    "assets/secret.wav",
    "assets/levelUP.wav",
    "assets/shift2.wav",
    "assets/triple.wav",
    "assets/place.wav",
    "assets/youWin.wav",
    "assets/zoneStart.wav",
    "assets/quad.wav",
    "assets/towerScroll.wav",
    "assets/perfectScroll.wav",
};

int SoundEffectIds[] = {
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
};
