#!/usr/bin/env python3

import os
directory = 'assets'

count = 0
music_count = 0

effect_list = []
game_music_list = []
menu_music_list = []

sep = '.'

for filename in os.listdir(directory):
    n = (filename.split(sep,1)[0]).upper()

    if(filename.find('.wav') != -1):
        path = "assets/" + filename
        name = "SFX_" + n;
        name = name.replace("-","_");
        effect_list.append((name,path))

        count+=1

    if(filename.find('.mod') != -1) or (filename.find('.it') != -1) or (filename.find('.xm') != -1):
        path = "assets/" + filename
        name = "MOD_" + n
        name = name.replace("-","_");
        name = name.replace("GAME_","");
        name = name.replace("MENU_","");

        if(filename.find('GAME_') != -1):
            game_music_list.append((name,path))
        else:
            menu_music_list.append((name,path))

        music_count+=1

def sortFunc(a):
    return a[0]

menu_music_list.sort(key=sortFunc)
game_music_list.sort(key=sortFunc)

with open("./include/audio_files.h","w") as header:
    header.write("//GENERATED BY buildSongs.py\n");
    header.write("//DO NOT EDIT DIRECTLY\n\n");
    header.write("#pragma once\n\n");

    header.write(f"#define SFX_COUNT {count}\n\n")
    header.write(f"extern const char * SoundEffectPaths[];\n")
    header.write(f"extern int SoundEffectIds[];\n")

    header.write("\nenum SoundEffects{\n")

    for item in effect_list:
        name = item[0]
        header.write(f"\t{name},\n")

    header.write("};\n\n")

    header.write("enum MenuSongs{\n")

    for item in menu_music_list:
        name = item[0]
        header.write(f"\t{name},\n")

    header.write("};\n\n")

    header.write("enum GameSongs{\n")

    for item in game_music_list:
        name = item[0]
        header.write(f"\t{name},\n")

    header.write("};\n\n")

with open("./source/audio_files.cpp","w") as source:
    source.write("//GENERATED BY buildSongs.py\n");
    source.write("//DO NOT EDIT DIRECTLY\n\n");

    source.write("#include \"audio_files.h\"\n\n");

    source.write("const char * SoundEffectPaths[] = {\n")

    for item in effect_list:
        path = item[1]
        source.write(f"\t\"{path}\",\n")

    source.write("};\n\n")

    source.write("int SoundEffectIds[] = {\n")
    for i in range(count):
        source.write(f"\t-1,\n")
    source.write("};\n")

with open("./tools/sound_effects.txt","w") as sfx_list:
    for item in effect_list:
        name = item[0]
        sfx_list.write(f"{name}\n")
