#pragma once

#include "def.h"
#define RUMBLE_SEQUENCE(name) name

#define DEFINE_RUMBLE_LIST \
    RUMBLE_SEQUENCE( RUMBLE_ZONE ), \
    RUMBLE_SEQUENCE( RUMBLE_ZONE_2 ), \
    RUMBLE_SEQUENCE( RUMBLE_ZONE_3 ), \
    RUMBLE_SEQUENCE( RUMBLE_ZONE_4 ), \
    RUMBLE_SEQUENCE( RUMBLE_ZONE_5 ), \
    RUMBLE_SEQUENCE( RUMBLE_ZONE_6 ), \
    RUMBLE_SEQUENCE( RUMBLE_LONG_ZONE ), \
    RUMBLE_SEQUENCE( RUMBLE_LONG_ZONE_2 ), \
    RUMBLE_SEQUENCE( RUMBLE_LONG_ZONE_3 ), \
    RUMBLE_SEQUENCE( RUMBLE_LEVEL_UP ), \
    RUMBLE_SEQUENCE( RUMBLE_PLACE ), \
    RUMBLE_SEQUENCE( RUMBLE_ZONE_RIPPLE ), \
    RUMBLE_SEQUENCE( RUMBLE_CLASSIC_CLEAR ), \
    RUMBLE_SEQUENCE( RUMBLE_SINGLE ), \
    RUMBLE_SEQUENCE( RUMBLE_DOUBLE ), \
    RUMBLE_SEQUENCE( RUMBLE_TRIPLE ), \
    RUMBLE_SEQUENCE( RUMBLE_QUAD ), \
    RUMBLE_SEQUENCE( RUMBLE_QUAD_B2B ), \
    RUMBLE_SEQUENCE( RUMBLE_TSPIN ), \
    RUMBLE_SEQUENCE( RUMBLE_TSPIN_B2B ), \
    RUMBLE_SEQUENCE( RUMBLE_TSPIN_MINI ), \
    RUMBLE_SEQUENCE( RUMBLE_PERFECT_CLEAR ), \
    RUMBLE_SEQUENCE( RUMBLE_COOL ), \
    RUMBLE_SEQUENCE( RUMBLE_REGRET ), \
    RUMBLE_SEQUENCE( RUMBLE_OCTORIS ), \
    RUMBLE_SEQUENCE( RUMBLE_DODECATRIS ), \
    RUMBLE_SEQUENCE( RUMBLE_DECAHEXATRIS ), \
    RUMBLE_SEQUENCE( RUMBLE_PERFECTRIS ), \
    RUMBLE_SEQUENCE( RUMBLE_ULTIMATRIS ), \
    RUMBLE_SEQUENCE( RUMBLE_ERR_2 ), \
    RUMBLE_SEQUENCE( RUMBLE_ERR_4 ), \
    RUMBLE_SEQUENCE( RUMBLE_YOUWIN ), \
    RUMBLE_SEQUENCE( RUMBLE_YOULOSE ), \
    RUMBLE_SEQUENCE( RUMBLE_TEST_DOUBLE ), \
    RUMBLE_SEQUENCE( RUMBLE_TEST_TRIPLE ), \
    RUMBLE_SEQUENCE( RUMBLE_SECRET )

enum RumbleSequence : int
{
    DEFINE_RUMBLE_LIST,

    RUMBLE_ARRAY_MAX,
    RUMBLE_NONE
};

void rumblePattern(const RumbleSequence sequence, int strength_mod = 0);
void rumblePatternLowPri(const RumbleSequence sequence, int strength_mod = 0);
void rumblePatternStop();
const RumbleSequence rumbleGetCurrent();
void rumblePatternLoop();
